# Generated by Django 2.1.5 on 2019-01-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecgsite', '0002_auto_20190113_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecgwave',
            name='file',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='vaulue',
            new_name='value',
        ),
        migrations.AddField(
            model_name='file',
            name='timeunit',
            field=models.CharField(default='s', max_length=15),
        ),
        migrations.AddField(
            model_name='file',
            name='voltageunit',
            field=models.CharField(default='mV', max_length=15),
        ),
        migrations.AlterField(
            model_name='point',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecgsite.File'),
        ),
        migrations.DeleteModel(
            name='Ecgwave',
        ),
    ]
